POST https://todo-server-lm1u.onrender.com/tasks
Content-Type: application/json

{
    "newText": "new route",
    "isChecked": true
}

###

GET https://todo-server-lm1u.onrender.com/tasks

### 

DELETE https://todo-server-lm1u.onrender.com/tasks/14
