// rota para adicionar dados na tabela tasks
POST http://localhost:3333/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pa2VQQVNTYWRkZCIsImlhdCI6MTczMTYwNzgyMSwiZXhwIjoxNzMxNjExNDIxfQ.EoeWujaJ54cH1O8wxSTbNrg1AIjCCJgLJUxLUF__870

{
    "newtext": "sou do banco",
    "isChecked": true
}

###
PUT  http://localhost:3333/tasks/2
Content-Type: application/json

{
    "newtext": "michael",
    "id": 2 
}

###
// rota para buscar dados na tabela tasks
GET http://localhost:3333/tasks

### 

//rota para deletar dados na tabela tasks
DELETE https://todo-server-gdw2.onrender.com/tasks


// rota para registrar dados na tabela users
###
POST https://todo-server-9m5t.onrender.com/register
Content-Type: application/json

{
  "username": "jhon",
  "email": "@jhon.com",
  "password": "jhon"
}

// buscar dados na tabela users
###
GET http://localhost:3333/register


### 
POST https://todo-server-9m5t.onrender.com/login
Content-Type: application/json

{
  "username": "jhon",
  "email": "@jhon.com",
  "password": "jhon"
}
