// rota para adicionar dados na tabela tasks
POST http://localhost:3333/tasks
Content-Type: application/json

{
    "newtext": "server",
    "isChecked": true
}

###
PUT  http://localhost:3333/tasks/2
Content-Type: application/json

{
    "newtext": "michael",
    "id": 2 
}


###
// rota para buscar dados na tabela tasks
GET http://localhost:3333/tasks

### 

//rota para deletar dados na tabela tasks
DELETE https://todo-server-gdw2.onrender.com/tasks


// rota para registrar dados na tabela users
###
POST http://localhost:3333/register
Content-Type: application/json

{
  "username": "michael",
  "email": "michael@exemplo.com",
  "password": "moranisdev"
}

// buscar dados na tabela users
###
GET http://localhost:3333/register

